Finalizar compra
IgorNascAlves/nossa-casa-do-codigo-fundamentos pull request #10
Opened 2020-06-17 19:39 UTC by IgorNascAlves

2020-06-18 14:00 UTC, wandersonmaceds requested changes

2020-06-18 14:00 UTC, wandersonmaceds commented on src/carrinho.py
> +        return self.cod_atual
Aqui, por que o finaliza compra não recebe um cliente diretamente? Não me parece fazer sentido um método do carrinho que cria o cliente. Aqui é uma mistura de responsabilidades.

2020-06-18 14:00 UTC, wandersonmaceds commented on src/cupons.py
> +            raise Exception("Cupom vencido")
Aqui confesso que não me soa bom que o cupom, um item de negócio, seja representado dessa forma, onde você tem regras associadas, mas elas fazem parte da mesma representação que armazena todos os cupons. É uma solução direta e funcional, mas é confuso pensar que onde eu quiser usar a ideia de cupon, eu leve não só a representação de um cupon, mas também de todos os cupons existentes.

2020-06-18 18:19 UTC, IgorNascAlves commented on src/cupons.py
> +            raise Exception("Cupom vencido")
A ideia dessa classe é que ela é a lista de cupons, ela vai armazenar os cupons e validar se eles existem e se estão vencidos.
O que posso fazer é criar uma classe Cupon que vai ter o nome e a validade invés de usar o dicionario que fica dentro da Classe Cupons.

2020-06-18 22:04 UTC, wandersonmaceds requested changes

2020-06-18 22:04 UTC, wandersonmaceds commented on src/cupons.py
> +            raise Exception("Cupom vencido")
Se o cupom em si, sabe de sua validade, por que um terceiro precisa conferir isso?

2020-06-18 22:04 UTC, wandersonmaceds commented on src/cupons.py
> +            raise Exception("Cupom vencido")
Acho que o próprio cupon deveria saber dizer se ele ainda é valido ou não.

2020-06-18 22:04 UTC, wandersonmaceds commented on src/cupons.py
> +            raise Exception("Cupom vencido")
Qual é o desconto do cupom?

2020-06-18 22:04 UTC, wandersonmaceds commented on src/cupon.py
> +class Cupon:
Boa

2020-06-18 22:04 UTC, wandersonmaceds commented on src/cliente.py
> +class Cliente:
Boa

2020-06-19 16:56 UTC, wandersonmaceds approved these changes
Top, mandou bem!

2020-06-19 17:04 UTC, merged