metodo busca na Classe ColecaoDeAutores e 3 novos testes
IgorNascAlves/nossa-casa-do-codigo-fundamentos pull request #4
Opened 2020-03-10 14:59 UTC by IgorNascAlves

2020-03-10 15:42 UTC, wandersonmaceds requested changes
Cuidado com a implementação de coisas que não foram requisitadas. Normalmente isso vira um código morto: existe mas nenhuma parte da aplicação usa e se um método existe apenas para satisfazer um teste, quer dizer que pode haver alguma brecha na lógica da implementação que não bate com o que foi especificado.

2020-03-10 15:42 UTC, wandersonmaceds commented on src/colecaoAutor.py
> +        raise Exception("Autor não encontrado")
Ainda não temos a necessidade de buscar autores, certo? Então este código veio muito antes da necessidade dele. Pelo que entendi, está sendo usado apenas para conferir algo nos testes. Não batendo com nenhuma regra de negócio atual. 

Pro estagio atual, removeria. Inclusive seus testes.

2020-03-10 16:18 UTC, IgorNascAlves commented on src/colecaoAutor.py
> +        raise Exception("Autor não encontrado")
Eu tive dificuldade de entender o que era para ser feito nesse card.

"criar uma abstração que encapsule a lógica de inserção e busca dos autores cadastrados."
Nesse trecho entendi que foi proposto a busca dos autores. 

"crie/modifique os seus testes de unidade para verificar a inserção e listagem"
Nessa parte entendi a necessidade de criar um teste para o acesso da lista.

Acho que o meu engano é que no card anterior eu tinha que ter feito somente a regra do e-mail e então nesse card construir a parte de abstrair, que seria criar a Classe ColecaoDeAutores.

2020-03-11 00:51 UTC, wandersonmaceds commented on src/colecaoAutor.py
> +        raise Exception("Autor não encontrado")
Opa, seria um get da lista direto mesmo. Como não tem nada sobre busca ainda, o método se faz desnecessário, mas sim, é uma interpretação válida. A busca pode vir a acontecer depois e o card pode ter sido mal escrito nesse quesito.

2020-03-11 18:44 UTC, wandersonmaceds approved these changes
Boa, mandou bem! Segue pro próximo!

2020-03-12 12:37 UTC, merged