Criar um novo livro
IgorNascAlves/nossa-casa-do-codigo-fundamentos pull request #6
Opened 2020-04-03 17:33 UTC by IgorNascAlves

Implementação da Classe Livro e seus Testes

2020-04-06 21:31 UTC, wandersonmaceds requested changes

2020-04-06 21:31 UTC, wandersonmaceds commented on src/livro.py
> +        self._sumario = sumario
Acho que caiu no caso do sumario ser de tamanho livre, mas aqui você não valida nada, nem se ele existe, no, se é uma string no caso. Lembrando, tamanho livre não quer dizer que é opcional ou que pode ser um valor diferente de um texto.

2020-04-06 21:31 UTC, wandersonmaceds commented on src/livro.py
> +        return data
Se você tem uma lógica que não faz particularmente parte da criação ou da gestão do estado do livro, ela deve ficar fora. É o caso aqui, criar um objeto de data a partir de uma string não parece ser responsabilidade do Livro. Acho que vale a pena colocar essa lógica fora do livro.

2020-04-07 18:48 UTC, IgorNascAlves commented on src/livro.py
> +        self._sumario = sumario
Entendi, é que não falava nenhuma limitação no card, mas vou colocar essas regras "técnicas" mesmo se não estão no card.

2020-04-07 19:04 UTC, IgorNascAlves commented on src/livro.py
> +        return data
Gostei, seu questionamento me obrigou a buscar por outra solução e descobri que a biblioteca datetime já era capaz de transformar uma string de data para o tipo date.

2020-04-09 14:35 UTC, wandersonmaceds reviewed
Deixei só um comentário reflexivo, a escolha é sua fazer a alteração ou continuar assim. Se continuar, pelo menos será consciente. :)

2020-04-09 14:35 UTC, wandersonmaceds commented on src/livro.py
> +        if titulo in [None, '', ' ']:
Esse if tem se repetido bastante no código. Uma saída talvez seja isolar isso em uma função auxiliar externa onde você , com a lógica isolada, você possa fazer aqui algo como `if isNull(titulo) || isEmpty(titulo):`

2020-04-22 19:59 UTC, wandersonmaceds reviewed
Deixei comentários mais reflexivos, caso queira mudar, mude, caso não queira, pelo menos pensou a respeito.

2020-04-22 19:59 UTC, wandersonmaceds commented on src/colecaoLivro.py
> +            raise Exception("Livro com mesmo titulo ja existe")
Sua validação é de título e isbn, por que a mensagem considera só o título. Aqui, entra o caso de se for específicar o que pode dar errado, deixe todos os campos na mensagem. É tudo ou nada :)

2020-04-22 19:59 UTC, wandersonmaceds commented on src/livro.py
> +    return valor in [None, '', ' ']
Aqui faz sentido separar essa validação em um arquivo separado, o livro.py só deveria precisar de modificação se alguma regra relativa ao livro mudar. Inclusive, o _data_valida também não é de responsabilidade do Livro. Extrairia ele para outro arquivo também, podem ser funções em um arquivo tipo validation_utils.py

2020-04-23 18:04 UTC, IgorNascAlves commented on src/livro.py
> +    return valor in [None, '', ' ']
Fico na duvida de tirar isso de dentro da classe Livro, porque são as regras de negocio do Livro, por isso acredito que são responsabilidades dele.
O livro que exige que data de lançamento seja maior que o dia atual.
E o livro que exige que tenha um titulo e outros atributos validos.

2020-04-24 18:12 UTC, wandersonmaceds commented on src/livro.py
> +    return valor in [None, '', ' ']
Sim, mas não é específico de um livro, em outro contexto a regra pode ser a mesma, um número que não é nulo.

2020-04-24 19:16 UTC, wandersonmaceds approved these changes

2020-04-27 16:43 UTC, wandersonmaceds approved these changes
Boa mandou bem!

Agora, se no seu sistema, você troca a forma de validar se uma data é futura, você não precisa mudar todas as classes do sistema, altera apenas no validaton_utils e pimba, todo seu sistema continua saudável. 

Existe uma falta de consistência e algumas sugestões de nomenclaturas. `is_null_empty` por exemplo, não expressa muito bem a itenção da função, acho que `is_null_or_empty` deixa mais claro. E outra coisa é você nomear esse método em inglês o no outro usar português: `valida_se_data_futura`. 

Escolha uma forma e se segure nela :)

2020-04-29 12:09 UTC, wandersonmaceds approved these changes
Boa

2020-04-29 17:45 UTC, merged