Exiba os itens de forma única e com suas respectivas quantidades
IgorNascAlves/nossa-casa-do-codigo-fundamentos pull request #9
Opened 2020-06-03 16:47 UTC by IgorNascAlves

2020-06-04 12:47 UTC, wandersonmaceds requested changes

2020-06-04 12:47 UTC, wandersonmaceds commented on src/carrinho.py
>              raise Exception("Nao eh objeto da classe Livro")
Estranho, se você tipa o parametro como Livro, por que precisa checar com os isinstance?

2020-06-04 12:47 UTC, wandersonmaceds commented on src/carrinho.py
>          self.__total += livro.get_preco()
Aqui, sugiro você ter um método que calcula o total, do jeito que tá, seu código fica muito sensível a qualquer mudança de estratégia de calculo.

2020-06-04 12:47 UTC, wandersonmaceds commented on src/carrinho.py
> +        quant_livro = self.__lista.get(livro.get_titulo(), (0, 0.0))[0]
Confesso que não entendi essa linha.

2020-06-04 12:47 UTC, wandersonmaceds commented on src/carrinho.py
> +        self.__lista[livro.get_titulo()] = (quant_livro + 1, livro.get_preco())
Por que guardar apenas o título do livro e não o livro todo?

2020-06-04 16:32 UTC, IgorNascAlves commented on src/carrinho.py
>              raise Exception("Nao eh objeto da classe Livro")
No parâmetro eu utilizei um **Type Hints** e ele não gera erro quando não é respeitado, ele serve a apenas como guia para quem estiver usando a minha classe.
E utilizei o **isinstance** porque tinha acabado de aprender isso no curso de collections do Python e quis aplicar no projeto.

2020-06-04 16:37 UTC, IgorNascAlves commented on src/carrinho.py
>          self.__total += livro.get_preco()
Eu tinha implementado assim no [PR anterior](https://github.com/IgorNascAlves/nossa-casa-do-codigo-fundamentos/pull/8#discussion_r433869292).
Vou modificar, porque agora temos uma boa justificativa para separar esse trecho de código.

2020-06-05 12:00 UTC, wandersonmaceds commented on src/carrinho.py
>          self.__total += livro.get_preco()
No PR anterior a lógica do carrinho era mais simples, só adições sem quantidades, etc. Agora você sobra quantidade, multiplica o preço, etc.

2020-06-08 17:13 UTC, IgorNascAlves commented on src/carrinho.py
> +        quant_livro = self.__lista.get(livro.get_titulo(), (0, 0.0))[0]
Conversei com a Nádia e consegui simplificar essa logica e assim essa linha ficar mais legível.

2020-06-08 17:25 UTC, IgorNascAlves commented on src/carrinho.py
>          self.__total += livro.get_preco()
Entendi.
Eu adotei a logica de que sempre que adicionamos um livro no carrinho o total já aumenta com o valor desse livro, então não levo a quantidade de livros em consideração.
Entendo que ainda faz sentido não criar uma função para esse processo.

2020-06-09 12:03 UTC, wandersonmaceds approved these changes

2020-06-09 17:02 UTC, merged